# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP app to Azure Web App - learnapplication

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore ./LearningApp/LearningApp.csproj

      - name: Publish to folder
        run: dotnet publish ./LearningApp/LearningApp.csproj -c Release -o ./published

      - name: Zip published output
        run: powershell -Command "Compress-Archive -Path published/* -DestinationPath app.zip -Force"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ASP-app
          path: app.zip

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ASP-app
          path: 'ASP-app'
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CF3833B49A4C4149AA2A8B9EE5811A7C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0B12D282E264419F9E66DF3398A27322 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9654AD31186349FA83064D2852A16CF9 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'learnapplication'
          slot-name: 'Production'
          package: .

          
